import { UserCircle, Zap, Star, Crown } from "lucide-react";

export const APP_PLANS = [
  {
    id: "FREE",
    name: "Free",
    price: 0, // Valeur numérique pour le calcul
    priceDisplay: "0€",
    unit: "Gratuit",
    active: true,
    description: "Pour tester avec un seul bien.",
    features: ["Limité à 1 seul bail actif", "Quittances manuelles (PDF)", "Publicité", "❌ Pas d'envoi automatique"],
    icon: UserCircle,
    bgColor: "bg-slate-50",
    textColor: "text-slate-600",
    borderColor: "border-slate-200",
    btnColor: "bg-slate-800",
  },
  {
    id: "BASE",
    name: "Base",
    price: 2.00, // <--- C'EST CETTE VALEUR QUI RÈGLE TON PROBLÈME D'ESTIMATION
    priceDisplay: "2.00€",
    unit: "/ bail / mois",
    active: true,
    description: "L'essentiel administratif sans publicité.",
    features: ["Baux illimités", "Avis d'échéances auto", "Quittances en 1 clic", "Zéro publicité"],
    icon: Zap,
    bgColor: "bg-blue-50",
    textColor: "text-blue-600",
    borderColor: "border-blue-600",
    btnColor: "bg-blue-600",
  },
  {
    id: "PRO",
    name: "Pro",
    price: 5.00,
    priceDisplay: "5.00€",
    unit: "/ bail / mois",
    active: false,
    description: "L'automatisation et l'espace locataire.",
    features: ["Paiement CB automatique", "Espace Locataire", "Upload partagé", "Quittance auto"],
    icon: Star,
    bgColor: "bg-indigo-50",
    textColor: "text-indigo-600",
    borderColor: "border-indigo-600",
    btnColor: "bg-indigo-600",
    recommended: true,
  },
  {
    id: "EXPERT",
    name: "Expert",
    price: 8.00,
    priceDisplay: "8.00€",
    unit: "/ bail / mois",
    active: false,
    description: "Le prélèvement automatique total.",
    features: ["Prélèvement SEPA Auto", "Gestion des impayés", "Relance CB si échec", "Support 7j/7"],
    icon: Crown,
    bgColor: "bg-purple-50",
    textColor: "text-purple-600",
    borderColor: "border-purple-600",
    btnColor: "bg-purple-600",
  },
];